Refactor code

diff --git a/.github/workflows/appsignals-e2e-ec2-test.yml b/.github/workflows/appsignals-e2e-ec2-test.yml
--- a/.github/workflows/appsignals-e2e-ec2-test.yml
+++ b/.github/workflows/appsignals-e2e-ec2-test.yml
@@ -56,33 +56,29 @@ jobs:
           
           # Attempt to deploy the sample app on an EC2 instance and wait for its endpoint to come online. 
           # There may be occasional failures due to transitivity issues, so try up to 2 times. 
-          # Success of 0 indicates that both the terraform deployment and the endpoint are running, while 1 indicates
+          # deployment_failed of 0 indicates that both the terraform deployment and the endpoint are running, while 1 indicates
           # that it failed at some point
           retry_counter=0
           max_retry=2
-          success=1 
-          while [ $success -eq 1 ]; do
-            if [ $retry_counter -ge $max_retry ]; then
-              echo "Max retry reached, failed to deploy terraform and connect to the endpoint. Exiting code"
-              exit 1
-            fi
+          while [ $retry_counter -lt $max_retry ]; do
             echo "Attempt $retry_counter"
-            success=0
+            deployment_failed=0
             terraform apply -auto-approve \
               -var="aws_region=${{ env.AWS_DEFAULT_REGION }}" \
               -var="test_id=${{ env.TESTING_ID }}" \
               -var="sample_app_jar=${{ env.SAMPLE_APP_FRONTEND_SERVICE_JAR }}" \
               -var="sample_remote_app_jar=${{ env.SAMPLE_APP_REMOTE_SERVICE_JAR }}" \
               -var="cw_agent_rpm=${{ env.APP_SIGNALS_CW_AGENT_RPM }}" \
-              -var="adot_jar=${{ env.APP_SIGNALS_ADOT_JAR }}" || success=$?
+              -var="adot_jar=${{ env.APP_SIGNALS_ADOT_JAR }}" \
+            || deployment_failed=$?
           
-            if [ $success -eq 1 ]; then
+            if [ $deployment_failed -eq 1 ]; then
               echo "Terraform deployment was unsuccessful. Will attempt to retry deployment."
             fi
           
-            # If the success is still 0, then the terraform deployment succeeded and now try to connect to the endpoint.
+            # If the deployment_failed is still 0, then the terraform deployment succeeded and now try to connect to the endpoint.
             # Attempts to connect will be made for up to 10 minutes
-            if [ $success -eq 0 ]; then
+            if [ $deployment_failed -eq 0 ]; then
               echo "Attempting to connect to the endpoint"
               sample_app_endpoint=http://$(terraform output sample_app_main_service_public_dns):8080
               attempt_counter=0
@@ -90,7 +86,7 @@ jobs:
               until $(curl --output /dev/null --silent --head --fail $(echo "$sample_app_endpoint" | tr -d '"')); do
                 if [ ${attempt_counter} -eq ${max_attempts} ];then
                   echo "Failed to connect to endpoint. Will attempt to redeploy sample app."
-                  success=1
+                  deployment_failed=1
                   break
                 fi
           
@@ -102,12 +98,20 @@ jobs:
           
             # If the success is 1 then either the terraform deployment or the endpoint connection failed, so first destroy the
             # resources created from terraform and try again.
-            if [ $success -eq 1 ]; then
+            if [ $deployment_failed -eq 1 ]; then
               echo "Destroying terraform"
               terraform destroy -auto-approve \
                 -var="test_id=${{ env.TESTING_ID }}" 
           
               retry_counter=$(($retry_counter+1))
+            else
+              # If deployment succeeded, then exit the loop
+              break
+            fi
+          
+            if [ $retry_counter -eq $max_retry ]; then
+              echo "Max retry reached, failed to deploy terraform and connect to the endpoint. Exiting code"
+              exit 1
             fi
           done
 
