Remove nick-fields action due to known problems

diff --git a/.github/workflows/appsignals-e2e-eks-test.yml b/.github/workflows/appsignals-e2e-eks-test.yml
--- a/.github/workflows/appsignals-e2e-eks-test.yml
+++ b/.github/workflows/appsignals-e2e-eks-test.yml
@@ -115,28 +115,29 @@ jobs:
           ${{ env.SAMPLE_APP_NAMESPACE }}
 
       # Application pods need to be restarted for the
-      # app signals instrumentation to take effect
+      # app signals instrumentation to take effect. After restarting,
+      # check if we can establish connection with the sample app endpoint.
       - name: Restart the app pods and wait for the endpoints to come online
         id: restart-pod
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 3
-          retry_on: error
-          timeout_minutes: 6
-          shell: bash
-          # Restart the pod, then attempt to connect to the endpoint. It will try 30 times with 10 seconds delay. If
-          # it fails to establish connection, restart the pod and try again up to 3 tries.
-          command: |
-            kubectl delete pods --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
-            kubectl wait --for=condition=Ready pod --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
-            cd testing/terraform/eks
-            sample_app_endpoint=http://$(terraform output sample_app_endpoint)
-            cd ../../../              
-            curl --retry 30 --retry-delay 10 -s -o /dev/null $(echo "$sample_app_endpoint" | tr -d '"')
-            if [ $? != "0" ];then
-              echo "Failed to establish connection with endpoint"
+        run: |
+          retry_counter=0
+          max_retry=3
+          success=0
+          while [ $success -eq 0 ]; do
+            if [ $retry_counter -ge $max_retry ]; then
               exit 1
             fi
+            kubectl delete pods --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
+            kubectl wait --for=condition=Ready pod --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
+            sample_app_endpoint=http://$(terraform output sample_app_endpoint)
+            if ! $(curl --retry 30 --retry-delay 10 -s -o /dev/null $(echo "$sample_app_endpoint" | tr -d '"'));then
+              echo "Failed to establish connection with endpoint"
+              retry_counter=$(($retry_counter+1))
+            else
+              success=1
+            fi
+          done
+        working-directory: testing/terraform/eks
 
       - name: Get the sample app endpoint
         if: steps.restart-pod.outcome == 'success' && !cancelled()
