Release workflow

diff --git a/.github/workflows/release-build.yml b/.github/workflows/release-build.yml
--- a/.github/workflows/release-build.yml
+++ b/.github/workflows/release-build.yml
@@ -8,6 +8,7 @@ on:
 
 env:
   AWS_DEFAULT_REGION: us-east-1
+  TEST_TAG: public.ecr.aws/aws-observability/adot-autoinstrumentation-java:test
 
 permissions:
   id-token: write
@@ -51,6 +52,51 @@ jobs:
           GRGIT_USER: ${{ secrets.GITHUB_TOKEN }}
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
           GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
+
+      - name: Create checksum
+        run: |
+          echo ORIG_CHECKSUM="$(shasum otelagent/build/libs/aws-opentelemetry-agent-*.jar | awk '{ print $1 }')" >> "$GITHUB_ENV"
+
+      - name: Build and export to Docker
+        uses: docker/build-push-action@v4
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        with:
+          build-args: "ADOT_JAVA_VERSION=${{ env.ADOT_JAVA_VERSION }}"
+          context: .
+          load: true
+          tags: ${{ env.TEST_TAG }}
+
+      - name: Test docker image
+        shell: bash
+        run: |
+          docker volume create operator-volume
+          docker run --mount source=operator-volume,dst=/otel-auto-instrumentation adot-java-operator:${{ env.TEST_TAG }} cp /javaagent.jar /otel-auto-instrumentation/javaagent.jar
+          docker run -dt --mount source=operator-volume,dst=/otel-auto-instrumentation --name temp  public.ecr.aws/amazonlinux/amazonlinux:latest
+          FILENAME = $(docker exec temp /bin/bash -c "ls /otel-auto-instrumentation")
+          if [$FILENAME = javaagent.jar]; then
+            echo "javaagent.jar file was copied to the operator-volume"
+          else 
+            echo "error: javaagent.jar file was not copied to the operator-volume"
+            exit 1;
+          fi
+          CHECKSUM = $(docker exec temp /bin/bash -c "sha256sum /otel-auto-instrumentation/javaagent.jar | cut -d' ' -f1")
+          if [$CHECKSUM = $ORIG_CHECKSUM]; then
+            echo "copied javaagent.jar checksum matched"
+          else 
+            echo "error: copied javaagent.jar checksum mis-matched"
+            exit 1;
+          fi
+
+      - name: Build and push
+        uses: docker/build-push-action@v4
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        with:
+          push: true
+          build-args: "ADOT_JAVA_VERSION=${{ env.ADOT_JAVA_VERSION }}"
+          context: .
+          platforms: linux/amd64,linux/arm64
+          tags: |
+            public.ecr.aws/aws-observability/adot-autoinstrumentation-java:${{ env.ADOT_JAVA_VERSION }}, public.ecr.aws/aws-observability/adot-autoinstrumentation-java:latest
 
       - name: Create Release
         id: create_release
